environment:
  PY_DIR: C:\Python36-x64
  PYPI_PASSWORD:
    secure: ZuRCW1W45pqH03Lio54BzQ==
  GITHUB_TOKEN:
    secure: Q0/Pyd8J+EX6/zaOuWATGu2OvRBLz53SYEFejI91VFiPEOJ0KbyZl+2UdYSzniDI

skip_non_tags: true

image:
- Visual Studio 2015

platform:
  - x64

stack: python 3

clone_depth: 3

build: off

init:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%APPVEYOR_BUILD_FOLDER%\data\lib;%PATH%
  - cmd: set CNC_INSTALL_CNCA0_CNCB0_PORTS="YES"

install:
  - pip install twine

test_script:
  - cmake_build.cmd
  - python python\setup.py install

after_test:
  - pip install wheel
  - cd python && python setup.py sdist bdist_wheel

artifacts:
  - path: dist
    name: python_package
    type: zip

deploy_script:
  - ps: >-
      cd $env:APPVEYOR_BUILD_FOLDER\java\screen_recorder
      If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_BRANCH -eq "master") {
          (gc .\pom.xml).replace('0.0.1-SNAPSHOT',$env:APPVEYOR_REPO_TAG_NAME) | Out-File -encoding ASCII pom.xml
      }
      (gc .\settings.xml).replace('USER','Andrey1994') | Out-File -encoding ASCII settings.xml
      (gc .\settings.xml).replace('TOKEN',$env:GITHUB_TOKEN) | Out-File -encoding ASCII settings.xml
      mvn -s $env:APPVEYOR_BUILD_FOLDER\java-package\brainflow\settings.xml deploy -Dregistry=https://maven.pkg.github.com/brainflow-dev -Dtoken=$env:GITHUB_TOKEN
  - twine upload --skip-existing dist/*.whl --user Andrey1994 --password %PYPI_PASSWORD%

notifications:
  - provider: Email
    to:
      - a1994ndrey@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
