import enum


class RecorderExitCodes (enum.Enum):
    """Enum to store all possible exit codes"""

    STATUS_OK = 0
    NO_SUCH_PROCESS_ERROR = 100
    RECORDING_ALREADY_RUN_ERROR = 101
    RECORDING_THREAD_ERROR = 102
    RECORDING_THREAD_IS_NOT_RUNNING_ERROR = 103
    INVALID_ARGUMENTS_ERROR = 104
    SESSION_NOT_CREATED_ERROR = 105
    PREPARE_DESK_DUPL_ERROR = 106
    CREATE_TEXTURE_ERROR = 107
    DDA_CAPTURE_ERROR = 108
    FIND_WINDOW_ERROR = 109
    DDA_LOST_ACCESS_ERROR = 110
    DDA_TIMEOUT_ERROR = 111
    SYNC_TIMEOUT_ERROR = 112
    GENERAL_ERROR = 113
